Exception occured while logging Error IN DB - 
 Message -  A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - No connection could be made because the target machine actively refused it.) 
 Stacktrace -     at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location ---
   at CoreVisionDAL.Foundation.ErrorLogDALRoot.SaveErrorObjectInDb(ErrorLogRoot errorLog) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionDAL\Foundation\ErrorLogDALRoot.cs:line 108
   at CoreVisionBAL.Foundation.ErrorLogProcessRoot.SaveErrorObjectInDb(ErrorLogRoot errorLog) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionBAL\Foundation\ErrorLogProcessRoot.cs:line 29
   at CoreVisionBAL.ExceptionHandler.ErrorLogHandlerRoot.LogExceptionInDb(Exception ex, HttpContext currentContext) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionBAL\ExceptionHandler\ErrorLogHandlerRoot.cs:line 80Exception occured while logging Error IN DB - 
 Message -  A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 0 - The wait operation timed out.) 
 Stacktrace -     at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at CoreVisionDAL.Foundation.ErrorLogDALRoot.SaveErrorObjectInDb(ErrorLogRoot errorLog) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionDAL\Foundation\ErrorLogDALRoot.cs:line 108
   at CoreVisionBAL.Foundation.ErrorLogProcessRoot.SaveErrorObjectInDb(ErrorLogRoot errorLog) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionBAL\Foundation\ErrorLogProcessRoot.cs:line 29
   at CoreVisionBAL.ExceptionHandler.ErrorLogHandlerRoot.LogExceptionInDb(Exception ex, HttpContext currentContext) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionBAL\ExceptionHandler\ErrorLogHandlerRoot.cs:line 80Exception occured while logging Error IN DB - 
 Message -  A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SNI_PN11, error: 26 - Error Locating Server/Instance Specified) 
 Stacktrace -     at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at CoreVisionDAL.Foundation.ErrorLogDALRoot.SaveErrorObjectInDb(ErrorLogRoot errorLog) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionDAL\Foundation\ErrorLogDALRoot.cs:line 108
   at CoreVisionBAL.Foundation.ErrorLogProcessRoot.SaveErrorObjectInDb(ErrorLogRoot errorLog) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionBAL\Foundation\ErrorLogProcessRoot.cs:line 29
   at CoreVisionBAL.ExceptionHandler.ErrorLogHandlerRoot.LogExceptionInDb(Exception ex, HttpContext currentContext) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionBAL\ExceptionHandler\ErrorLogHandlerRoot.cs:line 80Exception occured while logging Error IN DB - 
 Message -  A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - No connection could be made because the target machine actively refused it.) 
 Stacktrace -     at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at CoreVisionDAL.Foundation.ErrorLogDALRoot.SaveErrorObjectInDb(ErrorLogRoot errorLog) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionDAL\Foundation\ErrorLogDALRoot.cs:line 108
   at CoreVisionBAL.Foundation.ErrorLogProcessRoot.SaveErrorObjectInDb(ErrorLogRoot errorLog) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionBAL\Foundation\ErrorLogProcessRoot.cs:line 29
   at CoreVisionBAL.ExceptionHandler.ErrorLogHandlerRoot.LogExceptionInDb(Exception ex, HttpContext currentContext) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionBAL\ExceptionHandler\ErrorLogHandlerRoot.cs:line 80Exception occured while logging Error IN DB - 
 Message -  A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - No connection could be made because the target machine actively refused it.) 
 Stacktrace -     at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location ---
   at CoreVisionDAL.Foundation.ErrorLogDALRoot.SaveErrorObjectInDb(ErrorLogRoot errorLog) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionDAL\Foundation\ErrorLogDALRoot.cs:line 108
   at CoreVisionBAL.Foundation.ErrorLogProcessRoot.SaveErrorObjectInDb(ErrorLogRoot errorLog) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionBAL\Foundation\ErrorLogProcessRoot.cs:line 29
   at CoreVisionBAL.ExceptionHandler.ErrorLogHandlerRoot.LogExceptionInDb(Exception ex, HttpContext currentContext) in D:\Personal-Projects\CoreVision\CoreVision\Components\CoreVisionBAL\ExceptionHandler\ErrorLogHandlerRoot.cs:line 80